FROM registry.access.redhat.com/ubi9/ubi-init:latest

# install tailscale
RUN dnf config-manager --add-repo https://pkgs.tailscale.com/stable/rhel/9/tailscale.repo \
    && dnf install -y \
        tailscale \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && sed -i 's/FLAGS=""/FLAGS="--tun=userspace-networking"/g' /etc/default/tailscaled \
    && systemctl enable tailscaled

# No need for entrypoint as base sets this
#ENTRYPOINT ["/sbin/init"]