FROM registry.fedoraproject.org/fedora:latest

LABEL org.opencontainers.image.title="Tailscale (systemd)" \
      org.opencontainers.image.description="Tailscale lets you securely connect to your containers without exposing them to the public internet." \
      org.opencontainers.image.authors="Gerard Braad"

# install tailscale
RUN dnf install -y \
        dnf-plugins-core \
        systemd \
    && dnf config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo \
    && dnf install -y \
        tailscale \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && sed -i 's/FLAGS=""/FLAGS="--tun=userspace-networking"/g' /etc/default/tailscaled \
    && systemctl enable tailscaled

ENTRYPOINT ["/sbin/init"]